name: grpc-example
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.6
    - protobuf
    - pip=9.0.1=py36_1
    - pip:
        - grpcio
        - grpcio-tools
