services:
    redis:
        image: "redis:alpine"
        ports: 
            - 6379:6379
    grpc-server:
        image: python-grpc-server
        ports:
            - 50051:50051
        environment:
            - PYTHONUNBUFFERED=1