# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import image_pb2 as image__pb2


class ImagePreprocessingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.facerecog = channel.unary_unary(
                '/ImagePreprocessing/facerecog',
                request_serializer=image__pb2.B64Image.SerializeToString,
                response_deserializer=image__pb2.UserInfo.FromString,
                )


class ImagePreprocessingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def facerecog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImagePreprocessingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'facerecog': grpc.unary_unary_rpc_method_handler(
                    servicer.facerecog,
                    request_deserializer=image__pb2.B64Image.FromString,
                    response_serializer=image__pb2.UserInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImagePreprocessing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImagePreprocessing(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def facerecog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ImagePreprocessing/facerecog',
            image__pb2.B64Image.SerializeToString,
            image__pb2.UserInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
